=== uwlib-cams/sinopia_maps/sinopia_maps.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- are both targetNamespace and xmlns attrs needed? -->
<xs:schema targetNamespace="https://uwlib-cams.github.io/sinopia_maps/"
    xmlns="https://uwlib-cams.github.io/sinopia_maps/"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" 
    elementFormDefault="qualified"
    vc:minVersion="1.1">
    
    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="http://www.w3.org/2001/03/xml.xsd"/>
    <xs:import namespace="http://www.w3.org/2001/XMLSchema"
        schemaLocation="https://www.w3.org/2001/XMLSchema.xsd"/>
    
    <!-- *****ROOT sinopia_maps***** -->
    <xs:element name="sinopia_maps" type="sinopia_maps_type"/>
    
    <xs:complexType name="sinopia_maps_type">
        <!-- may wish to add a mechanism for assembling RTs into a WEMI/WEM 'profile' -->
        <xs:sequence>
            <xs:element name="rts" type="rts_type" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="html_profiles" type="html_profiles_type" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- ****rts**** -->
    <xs:complexType name="rts_type">
        <xs:sequence>
            <xs:element name="rt" type="rt_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="rt_type">
        <xs:sequence>
            <!-- TO DO need some kind of ID which can be referenced by html_profile elements -->
            <xs:element name="prop_set" type="prop_set_type" minOccurs="1" maxOccurs="unbounded"/>
            <!-- [?] does it *really* make sense to prompt entry of anything other than an IRI for resource_type?? -->
            <xs:element name="resource" type="resource_type"/>
            <xs:element name="suppressible" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
            <!-- may want to further constrain values for optional_class later... -->
            <xs:element name="optional_class" type="xs:anyURI" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="format" type="format_type"/>
            <xs:element name="user" type="user_type"/>
            <xs:element name="author" type="author_type" minOccurs="1" maxOccurs="unbounded"/>
            <!-- may wish to add RT-level admin metadata here at some point, remark would go here in the sinopia_maps.xml instance -->
        </xs:sequence>
    </xs:complexType>
    
    <!-- enumerations for data_source, resource, format, and user will be duplicative of enumerations in
    map_storage.xsd, and will require updating in two places. 
    Possible to put in the same place and only update once?? -->
    
    <xs:simpleType name="prop_set_type">
        <!-- = map_storage.xsd mapid_prop_set_attr_type -->
        <xs:restriction base="xs:string">
            <xs:enumeration value="rdacWork"/>
            <xs:enumeration value="rdacExpression"/>
            <xs:enumeration value="rdacManifestation"/>
            <!-- Not yet in test storage instance
            <xs:enumeration value="rdacIPropSet"/>
            <xs:enumeration value="rdacAPropSet"/>
            <xs:enumeration value=""/>
            ... etc... -->
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="resource_type">
        <!-- = map_storage.xsd > mapid_resource_attr_type -->
        <xs:restriction base="xs:string">
            <xs:enumeration value="rdacWork"/>
            <xs:enumeration value="rdacExpression"/>
            <xs:enumeration value="rdacManifestation"/>
            <!-- Not yet in test storage instance
            <xs:enumeration value="rdacItem"/>
            <xs:enumeration value="rdacAgent"/>
            <xs:enumeration value=""/>
            -->
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="format_type">
        <!-- = map_storage.xsd > format_type -->
        <xs:restriction base="xs:string">
            <!-- mapid enumerations here will need updating -->
            <xs:enumeration value="monograph"/>
            <!-- below are for testing, to do delete from schema later -->
            <xs:enumeration value="test_literal_props"/>
            <xs:enumeration value="test_uri_or_lookup_props"/>
            <xs:enumeration value="test_nested_resource_props"/>
            <xs:enumeration value="test_all_props"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="user_type">
        <!-- = map_storage.xsd > user_type -->
        <xs:restriction base="xs:string">
            <!-- enumerations here will need updating -->
            <xs:enumeration value="default"/>
            <xs:enumeration value="ries07"/>
            <xs:enumeration value="mcm104"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="author_type">
        <!-- tried some annotation, shows up in the editor on mouseover in the sinopia_maps.xml instance -->
        <xs:annotation>
            <xs:documentation>Provide the name and/or email address of an author (or authors, in repeating elements) for the resource template.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    
    <!-- ****html_profiles**** -->
    <xs:complexType name="html_profiles_type">
        <xs:sequence>
            <xs:element name="html_profile" type="html_profile_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="html_profile_type">
        <!-- html profile elements should "bundle" rts together, using some kind of reference for the rt -->
    </xs:complexType>
    
</xs:schema>

=== uwlib-cams/sinopia_maps/sinopia_maps.xml
<?xml version="1.0" encoding="UTF-8"?>
<sinopia_maps xmlns="https://uwlib-cams.github.io/sinopia_maps/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://uwlib-cams.github.io/sinopia_maps/ 
    https://uwlib-cams.github.io/sinopia_maps/sinopia_maps.xsd">
    <rts>
        <rt>
            <propSet>rdacManifestation</propSet>
            <resource>rdacManifestation</resource>
            <format>test_literal_props</format>
            <user>ries07</user>
            <author>Benjamin Riesenberg / ries07@uw.edu</author>
        </rt>
        <rt>
            <propSet>rdacManifestation</propSet>
            <resource>rdacManifestation</resource>
            <format>test_uri_or_lookup_props</format>
            <user>ries07</user>
            <author>Benjamin Riesenberg / ries07@uw.edu</author>
        </rt>
        <rt>
            <propSet>rdacManifestation</propSet>
            <resource>rdacManifestation</resource>
            <format>test_nested_resource_props</format>
            <user>ries07</user>
            <author>Benjamin Riesenberg / ries07@uw.edu</author>
        </rt>
    </rts>
</sinopia_maps>

=== uwlib-cams/sinopia_maps/xml/sinopia_maps.xml
<?xml version="1.0" encoding="UTF-8"?>
<sinopia_maps xmlns="https://uwlib-cams.github.io/sinopia_maps/xsd/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://uwlib-cams.github.io/sinopia_maps/xsd/ https://uwlib-cams.github.io/sinopia_maps/xsd/sinopia_maps.xsd">
    <rts>
        <!-- WEMI TEMPLATES -->
        <rt>
            <institution>WAU</institution>
            <resource>rdaWork</resource>
            <format>printMonograph</format>
            <user>CAMS</user>
            <author>UW CAMS - ries07@uw.edu</author>
        </rt>
		<rt>
            <institution>WAU</institution>
            <resource>rdaExpression</resource>
		    <format>printMonograph</format>
            <user>CAMS</user>
		    <author>UW CAMS - ries07@uw.edu</author>
        </rt>
        <rt>
            <institution>WAU</institution>
            <resource>rdaManifestation</resource>
            <format>printMonograph</format>
            <user>CAMS</user>
            <author>UW CAMS - ries07@uw.edu</author>
        </rt>
        <rt>
            <institution>WAU</institution>
            <resource>rdaItem</resource>
            <format>printMonograph</format>
            <user>CAMS</user>
            <author>UW CAMS - ries07@uw.edu</author>
        </rt>
        
        <rt>
            <institution>WAU</institution>
            <resource>rdaWork</resource>
            <format>metadata_nested</format>
            <user>CAMS</user>
            <author>UW CAMS - ries07@uw.edu</author>
        </rt>
        
        <!-- AGENT TEMPLATES -->
        <rt>
            <institution>WAU</institution>
            <resource>rdaAgent</resource>
            <format>nested</format>
            <user>CAMS</user>
            <author>UW CAMS - ries07@uw.edu</author>
        </rt>
        
       <!-- NOMEN TEMPLATES -->        
        <rt>
            <institution>WAU</institution>
            <resource>rdaNomen</resource>
            <format>nested</format>
            <user>CAMS</user>
            <author>UW CAMS - mcm104@uw.edu</author>
        </rt>
        
        <!-- PLACE TEMPLATES -->
        <rt>
            <institution>WAU</institution>
            <resource>rdaPlace</resource>
            <format>nested</format>
            <user>CAMS</user>
            <author>UW CAMS - ries07@uw.edu</author>
        </rt>
        
        <!-- TIMESPAN TEMPLATES -->
        <rt>
            <institution>WAU</institution>
            <resource>rdaTimespan</resource>
            <format>nested</format>
            <user>CAMS</user>
            <author>UW CAMS - ries07@uw.edu</author>
        </rt>
        
        <!-- TEST TEMPLATES -->
        
        <rt>
            <institution>WAU</institution>
            <resource>rdaPlace</resource>
            <format>test</format>
            <user>cspayne</user>
            <author>Cypress Payne - cspayne@uw.edu</author>
        </rt>
        <rt>
            <institution>WAU</institution>
            <resource>rdaWork</resource>
            <format>test</format>
            <user>cspayne</user>
            <author>Cypress Payne - cspayne@uw.edu</author>
        </rt>
        
        <!-- ...future templates -->
        <!--
        <rt>
            <institution>WAU</institution>
            <resource>rdaCollectiveAgent</resource>
            <format>nested</format>
            <user>CAMS</user>
            <author>UW CAMS - ries07@uw.edu</author>
        </rt>
        <rt>
            <institution>WAU</institution>
            <resource>rdaPerson</resource>
            <format>nested</format>
            <user>CAMS</user>
            <author>UW CAMS - ries07@uw.edu</author>
        </rt>
        <rt>
            <institution>WAU</institution>
            <resource>rdaCorporateBody</resource>
            <format>nested</format>
            <user>CAMS</user>
            <author>UW CAMS - ries07@uw.edu</author>
        </rt>
        <rt>
            <institution>WAU</institution>
            <resource>rdaFamily</resource>
            <format>nested</format>
            <user>CAMS</user>
            <author>UW CAMS - ries07@uw.edu</author>
        </rt>
         -->
    </rts>
</sinopia_maps>
